use_frameworks!


target 'TGTextToSpeech_Example' do
  pod 'TGTextToSpeech', :path => '../'

  target 'TGTextToSpeech_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
deployment_target = '13.0'
#以下在M1的mac上需要使用
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
#                config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"  不加这个可以模拟器运行
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
